"""Initial migration

Revision ID: 688a49fbb849
Revises: 
Create Date: 2024-01-09 21:54:51.409881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688a49fbb849'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fusername', sa.String(length=64), nullable=True),
    sa.Column('fpassword_hash', sa.String(length=255), nullable=True),
    sa.Column('femail', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('rechtsform', sa.String(length=64), nullable=True),
    sa.Column('sitz', sa.String(length=64), nullable=True),
    sa.Column('leitung', sa.String(length=64), nullable=True),
    sa.Column('mitarbeiterzahl', sa.Integer(), nullable=True),
    sa.Column('umsatz', sa.String(length=64), nullable=True),
    sa.Column('branche', sa.String(length=64), nullable=True),
    sa.Column('is_firma', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firma_femail'), ['femail'], unique=True)
        batch_op.create_index(batch_op.f('ix_firma_fusername'), ['fusername'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('vorname', sa.String(length=64), nullable=True),
    sa.Column('nachname', sa.String(length=64), nullable=True),
    sa.Column('alter', sa.Integer(), nullable=True),
    sa.Column('beruf', sa.String(length=64), nullable=True),
    sa.Column('qualifikation', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stellenbezeichnung', sa.String(length=64), nullable=True),
    sa.Column('qualifikationen', sa.String(length=64), nullable=True),
    sa.Column('standort', sa.String(length=64), nullable=True),
    sa.Column('arbeitszeit', sa.String(length=64), nullable=True),
    sa.Column('vertrag', sa.String(length=64), nullable=True),
    sa.Column('vergütung', sa.String(length=64), nullable=True),
    sa.Column('bewerbungsfrist', sa.String(length=64), nullable=True),
    sa.Column('kontaktinformationen', sa.String(length=64), nullable=True),
    sa.Column('submit', sa.String(length=64), nullable=True),
    sa.Column('cancel', sa.String(length=64), nullable=True),
    sa.Column('stellenbeschreibung', sa.Text(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firma_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_stellenbezeichnung'), ['stellenbezeichnung'], unique=False)

    op.create_table('user_follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'firma_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follows')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_stellenbezeichnung'))

    op.drop_table('job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firma_fusername'))
        batch_op.drop_index(batch_op.f('ix_firma_femail'))

    op.drop_table('firma')
    # ### end Alembic commands ###
